import { useState, useRef, useEffect, ButtonHTMLAttributes } from "react";
import Head from "next/head";
import detectProvider from "@metamask/detect-provider";
import { ethers } from "ethers";
import styles from "../styles/Home.module.css";

const useComponentWillMount = (func: () => void) => {
  const willMount = useRef(true);

  if (willMount.current) func();

  willMount.current = false;
};

export default function Home() {
  const [metamask, setMetamask] = useState<any>({});
  const [user, setUser] = useState<string>("");
  const [isConnected, setIsConnected] = useState<boolean>(false);

  // Check if Metamask is present and connected.
  useComponentWillMount(async () => {
    const ethereum: any = await detectProvider({ mustBeMetaMask: true });
    if (ethereum) {
      setMetamask(ethereum);

      if (ethereum.selectedAddress) {
        setUser(ethereum.selectedAddress.slice(2));
        setIsConnected(true);
      }
    }
  });

  // Load the icon generator script.
  useEffect(() => {
    if (isConnected && !document.getElementById("jdenticon")) {
      const jdenticon = document.createElement("script");
      jdenticon.id = "jdenticon";
      jdenticon.src =
        "https://cdn.jsdelivr.net/npm/jdenticon@3.1.0/dist/jdenticon.min.js";
      jdenticon.integrity =
        "sha384-VngWWnG9GS4jDgsGEUNaoRQtfBGiIKZTiXwm9KpgAeaRn6Y/1tAFiyXqSzqC8Ga/";
      jdenticon.crossOrigin = "anonymous";
      document.body.appendChild(jdenticon);
    }
  }, [isConnected]);

  const handleConnect: React.MouseEventHandler<HTMLButtonElement> = async () => {
    const [address] = await metamask.request({
      method: "eth_requestAccounts",
    });

    if (address) {
      setUser(address.slice(2));
      setIsConnected(true);
    }
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>Brackets by Orballo</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <h1 className={styles.title}>Brackets</h1>

        {isConnected ? (
          <>
            <p>{user}</p>
            <svg
              className={styles["user-icon"]}
              width="128"
              height="128"
              data-jdenticon-hash={user}
            />
          </>
        ) : (
          !!metamask && (
            <button onClick={handleConnect}>Connect with MetaMask</button>
          )
        )}
      </main>
    </div>
  );
}
